robot_id: fr3
menagerie_model: franka_fr3
scene_xml_path: mujoco_menagerie/franka_fr3/scene.xml
controlled_joints:
  - fr3_joint1
  - fr3_joint2
  - fr3_joint3
  - fr3_joint4
  - fr3_joint5
  - fr3_joint6
  - fr3_joint7
action_mode: position
camera_defaults:
  - name: third_person
    pos: [1.2, -1.2, 0.9]
    quat: [0.856, 0.217, 0.372, 0.274]
    fovy: 45.0
    width: 84
    height: 84
eef_site_name: attachment_site
action_scale: 0.2
